# my-project/ansible/roles/semaphore_install/defaults/main.yml
semaphore_version: "2.8.77"
semaphore_user: "semaphore"
semaphore_port: 3000
semaphore_db_name: "semaphore"
semaphore_db_user: "semaphore"
semaphore_db_host: "127.0.0.1"
semaphore_db_port: 3306
semaphore_service_name: "semaphore"
